[package]
name         = "cryptobox"
version      = "0.6.0"
authors      = ["Roman S. Borschel <roman@pkaboo.org>", "Toralf Wittner <tw@dtex.org>"]
description  = "High-level API for proteus with persistent storage."
homepage     = "https://github.com/shared-secret/cryptobox"
repository   = "git@github.com:shared-secret/cryptobox.git"
license      = "MPL-2.0"

[dependencies]
byteorder  = ">  0.3.0"
cbor-codec = ">= 0.4.1"

[dependencies.proteus]
git    = "https://github.com/shared-secret/proteus"
branch = "develop"
